database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver
  # the username
  user: recipes
  # the password
  password: dlqDo!&Ov&5a=R`optE:;z2v"HU!#A9198a!wD
  # the JDBC URL
  url: jdbc:postgresql://127.0.0.1/recipes
  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

logging:
  level: INFO
  loggers:
    "fr.ggautier.recipes": ALL
    "org.hibernate.SQL": DEBUG
    "org.glassfish.jersey.logging": DEBUG
    "org.hibernate.engine.internal.StatisticalLoggingSessionEventListener": WARN
  appenders:
    - type: console
      threshold: ALL
      timeZone: Europe/Paris
      target: stdout