server:
  type: simple
  applicationContextPath: ${APP_PATH}
  adminContextPath: ${ADMIN_PATH}
  connector:
    type: http
    port: ${PORT}

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver
  # the username
  user: ${DB_USER}
  # the password
  password: ${DB_PWD}
  # the JDBC URL
  url: ${DB_URL}
  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

logging:
  level: INFO
  loggers:
    "fr.ggautier.recipes": ALL
    "org.glassfish.jersey.logging": DEBUG
    "org.hibernate.engine.internal.StatisticalLoggingSessionEventListener": WARN
  appenders:
    - type: file
      currentLogFilename: ${LOG_FILE}
      archivedLogFilenamePattern: ${LOG_FILE_PATTERN}
      archivedFileCount: ${MAX_LOG_FILES}
      archive: true
      threshold: ALL
      timeZone: Europe/Paris